### PR TITLE
Fix input formatters, changing base voltage in coil calculator

### LINKED ISSUE #48: Add ability to change base voltage
This value should be customizable. It's stored in `models/coil.ts` as `baseVoltage` variable. So just add reducer for `coil/setBaseVoltage`

Screenshot_2020-02-22_at_18 58 20

### PR DESCRIPTION
**Pull request by Argeath**
image

### CODE REVIEW

**Comment by stasbar** [comment]
This base voltage input is too verbose, and it's related only to properties, so It will be better to place it in the Properties section. I believe this value is changed by less than 1% of the users, so it should not be indicated as slightly as possible.

File: src/models/coil.ts [hunk 1]
```diff
@@ -96,43 +91,34 @@ const initialState: CoilModelState = {
   baseVoltage: 3.7,
 };
 
+function* calculateEffect(call, coil, cancel, put, method) {
```
Comment (stasbar) [inline src/models/coil.ts:94]: Please reorder to coil with call and add types to those arguments

Comment (stasbar) [reply src/models/coil.ts:94]: @Argeath
